apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: gifffy-com
  namespace: giffy
spec:
  secretName: web-server-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - gifffy.com
  acme:
    config:
    - dns01:
        provider: prod-dns
      domains:
      - gifffy.com