kind: Service
apiVersion: v1
metadata:
  name: web-server
spec:
  type: LoadBalancer
  selector:
    role: web-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 443
    targetPort: 443