kind: Service
apiVersion: v1
metadata:
  name: web-server
spec:
  type: LoadBalancer
  selector:
    role: web-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443